FROM python:3.10

# set work directory
WORKDIR /var/www/html

# set environment variables
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1

COPY ./app  .
COPY ./start.sh .


RUN rm -rf virtualEnv \
    && apt-get update \
    && apt-get -y install libpq-dev gcc \
    && mkdir gunicorn_logs \
    && pip install --upgrade pip \
    && pip install -r requirements.txt \
    && chmod +x ./start.sh
    
    
CMD ["/var/www/html/start.sh"]