version: '3.1'

services:

  frontend:
    build: ./frontend
    container_name: frontend
    expose:
      - 8080
    networks:
      - project_network
  
  
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - frontend
    ports:
      - 80:80
    networks:
      - project_network

networks:
  project_network:

