version: '3.1'

services:
  # Database
  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_HOST: localhost
      MYSQL_ROOT_HOST: '%'
      MARIADB_ROOT_PASSWORD: pass
      MYSQL_DATABASE: testdb
    volumes: 
      - ./docker/mysqldata_push:/var/lib/mysql
    expose:
      - 3306
    networks:
      - peroject_network
  
  djangoweb:
    build: ./backend
    container_name: djangoweb
    env_file:
      - ./.env
    depends_on:
      - db
    expose:
      - 8000
    networks:
      - peroject_network
  
  nginx:
    build: ./nginx
    container_name: nginx
    depends_on:
      - djangoweb
      - db
    ports:
      - 80:80
    networks:
      - peroject_network

networks:
  peroject_network:

